
[functions.check-task-deadlines]
enabled = true
verify_jwt = true
import_map = "./functions/check-task-deadlines/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-task-deadlines/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-task-deadlines/*.html" ]
